### ISSUE TITLE
Unable to Install in .Net Framework 4.5

### ISSUE THREAD

**Issue by zahid119** [bmak91/fcm-push-notification#1]
Install-Package : Could not install package 'ACB.FCMPushNotifications 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but 
the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package ACB.FCMPushNotifications
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by bmak91** [comment]
Hi, this library is specifically targeting an "ASP.Net Core" application running on ".Net Core" (see [difference between ".Net Framework" and ".Net Core"](http://www.c-sharpcorner.com/article/difference-between-net-framework-and-net-core/))

I have no plans to add support for ".Net Framework" at this time, but I think you should be able to adapt a large portion of the code to work with your app, as the only parts that are really specific to Core are the configuration, and taking advantage of dependency injection out of the box.

**Comment by zahid119** [comment]
Thanks. The problem was with nuget package manager. I tried in in new project and it worked.
