### ISSUE TITLE
Sintax error

### ISSUE THREAD

**Issue by karaipyhare** [bmak91/fcm-push-notification#2]
There is a sintax error at your ConfigureServices method:

At these lines:
services.AddDbContext<NotifServerDbContext>(builder =>
			builder.UseSqlServer(CONNECTION_STRING, options =>
				builder.MigrationsAssembly(ASSEMBLY_NAME))
		);
...this part:
options =>builder.MigrationsAssembly(ASSEMBLY_NAME)

...must be:

options =>options .MigrationsAssembly(ASSEMBLY_NAME)

Regards.

**Comment by bmak91** [comment]
Ha! True, silly mistake. Thanks for reporting, will fix soon 😃
